name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: add MUSL target
      run: rustup target add --toolchain stable x86_64-unknown-linux-musl
    - name: Build for Docker
      run: cargo build --target=x86_64-unknown-linux-musl --release
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      uses: docker/login-action@v1.12.0
      with:
        username: corentinway
        password: ${{ secrets.DOCKERHUB_PAT }}
        
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
      uses: docker/build-push-action@v2.9.0
      with:       
        # List of build-time variables
        build-args: -t corentinway/permutation_web_server
        # List of tags
        tags: no-prod
        context: /home/runner/work/permutation_web_server/permutation_web_server/
        push: true
        
